"""
Domain entities for meal planning module.

These are pure Python dataclasses representing the core business concepts.
They are independent of ORM models and can be used throughout the application.
"""
from dataclasses import dataclass, field
from typing import Callable, Awaitable, List, Optional
from uuid import UUID


# Type alias for progress callbacks used during plan generation
ProgressCallback = Callable[[dict], Awaitable[None]]


@dataclass
class UserProfile:
    """
    User profile containing daily nutritional targets for meal planning.

    This entity is derived from user data and preferences, containing
    calculated daily targets used by the meal planner.

    Attributes:
        user_id: Reference to the user
        daily_kcal: Target daily calories
        daily_protein: Target daily protein in grams
        daily_fat: Target daily fat in grams
        daily_carbs: Target daily carbohydrates in grams
        preferences: Additional preferences (diet, allergies, etc.)
    """
    user_id: UUID
    daily_kcal: int
    daily_protein: float
    daily_fat: float
    daily_carbs: float
    preferences: dict = field(default_factory=dict)


@dataclass
class MealTemplate:
    """
    Template for a single meal before ingredient selection.

    Generated by LLM as the first step of plan generation,
    containing target macros and a general description.

    Attributes:
        meal_type: Type of meal (breakfast, second_breakfast, lunch, snack, dinner)
        target_kcal: Target calories for this meal
        target_protein: Target protein in grams
        target_fat: Target fat in grams
        target_carbs: Target carbohydrates in grams
        description: Short description of the meal concept (e.g., "Owsianka z owocami")
        ingredient_keywords: List of ingredient keywords for focused product search
                            (e.g., ["chleb", "twarog", "rzodkiewka"] for "Kanapki z twarogiem")
    """
    meal_type: str
    target_kcal: int
    target_protein: float
    target_fat: float
    target_carbs: float
    description: str
    ingredient_keywords: List[str] = field(default_factory=list)


@dataclass
class GeneratedIngredient:
    """
    A single ingredient in a generated meal.

    Represents an ingredient with its nutritional values calculated
    for the specific amount used in the meal.

    Attributes:
        food_id: Reference to food catalogue (None for custom ingredients)
        name: Display name of the ingredient
        amount_grams: Amount in grams
        unit_label: Optional display label (e.g., "1 szklanka", "2 łyżki")
        kcal: Calories for the amount
        protein: Protein in grams for the amount
        fat: Fat in grams for the amount
        carbs: Carbohydrates in grams for the amount
    """
    food_id: Optional[UUID]
    name: str
    amount_grams: float
    unit_label: Optional[str]
    kcal: float
    protein: float
    fat: float
    carbs: float


@dataclass
class GeneratedMeal:
    """
    A complete generated meal with ingredients.

    Contains all details of a meal including its ingredients
    and aggregated nutritional values.

    Attributes:
        meal_type: Type of meal (breakfast, second_breakfast, lunch, snack, dinner)
        name: Name of the meal/recipe
        description: Brief description or preparation notes
        preparation_time_minutes: Estimated preparation time
        ingredients: List of ingredients in this meal
        total_kcal: Total calories (sum of ingredients)
        total_protein: Total protein in grams
        total_fat: Total fat in grams
        total_carbs: Total carbohydrates in grams
    """
    meal_type: str
    name: str
    description: str
    preparation_time_minutes: int
    ingredients: List[GeneratedIngredient]
    total_kcal: float
    total_protein: float
    total_fat: float
    total_carbs: float


@dataclass
class GeneratedDay:
    """
    A day's worth of meals in a generated plan.

    Contains all meals for a single day with computed totals.

    Attributes:
        day_number: Day number within the plan (1-indexed)
        meals: List of meals for this day
    """
    day_number: int
    meals: List[GeneratedMeal]

    @property
    def total_kcal(self) -> float:
        """Total calories for the day."""
        return sum(m.total_kcal for m in self.meals)

    @property
    def total_protein(self) -> float:
        """Total protein for the day in grams."""
        return sum(m.total_protein for m in self.meals)

    @property
    def total_fat(self) -> float:
        """Total fat for the day in grams."""
        return sum(m.total_fat for m in self.meals)

    @property
    def total_carbs(self) -> float:
        """Total carbohydrates for the day in grams."""
        return sum(m.total_carbs for m in self.meals)


@dataclass
class GeneratedPlan:
    """
    Complete generated meal plan.

    The final output of the meal plan generation process,
    containing multiple days of meals and metadata.

    Attributes:
        days: List of generated days
        preferences_applied: Preferences that were used during generation
        generation_metadata: Additional metadata from generation process
    """
    days: List[GeneratedDay]
    preferences_applied: dict
    generation_metadata: dict = field(default_factory=dict)


@dataclass
class PlanPreferences:
    """
    User preferences for meal plan generation.

    Controls how the meal plan is generated, including dietary
    restrictions, allergies, and cooking constraints.

    Attributes:
        diet: Diet type (e.g., "vegetarian", "vegan", "keto")
        allergies: List of allergens to avoid
        cuisine_preferences: Preferred cuisines (defaults to ["polish"])
        excluded_ingredients: Specific ingredients to exclude
        max_preparation_time: Maximum preparation time per meal in minutes
    """
    diet: Optional[str] = None
    allergies: List[str] = field(default_factory=list)
    cuisine_preferences: List[str] = field(default_factory=lambda: ["polish"])
    excluded_ingredients: List[str] = field(default_factory=list)
    max_preparation_time: Optional[int] = None
