"""extract_units_to_table

Revision ID: 053a4505bb2d
Revises: 663fa3a6501b
Create Date: 2026-01-20 23:35:06.117300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '053a4505bb2d'
down_revision: Union[str, Sequence[str], None] = '663fa3a6501b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_units',
    sa.Column('food_id', sa.Uuid(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_units_food_id'), 'food_units', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_units_id'), 'food_units', ['id'], unique=False)
    op.drop_column('foods', 'units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('units', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_food_units_id'), table_name='food_units')
    op.drop_index(op.f('ix_food_units_food_id'), table_name='food_units')
    op.drop_table('food_units')
    # ### end Alembic commands ###
