"""Add profile fields

Revision ID: 161f1645f125
Revises: 588b69e99774
Create Date: 2026-01-12 18:48:25.355540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161f1645f125'
down_revision: Union[str, Sequence[str], None] = '588b69e99774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('goal', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('activity_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activity_level')
    op.drop_column('user', 'goal')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'height')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    op.drop_column('user', 'is_onboarded')
    # ### end Alembic commands ###
