"""Add gi_per_100g to meal_plan_ingredients

Revision ID: 1f6dfdb2d0cc
Revises: j8k9l0m1n2o3
Create Date: 2026-02-20 19:42:13.537039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6dfdb2d0cc'
down_revision: Union[str, Sequence[str], None] = 'j8k9l0m1n2o3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_ingredients', sa.Column('gi_per_100g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan_ingredients', 'gi_per_100g')
    # ### end Alembic commands ###
