"""Add verification code

Revision ID: 588b69e99774
Revises: 8fa605be32d8
Create Date: 2026-01-12 18:23:11.578861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588b69e99774'
down_revision: Union[str, Sequence[str], None] = '8fa605be32d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    # ### end Alembic commands ###
