"""add_category_units_to_foods

Revision ID: 663fa3a6501b
Revises: 161f1645f125
Create Date: 2026-01-20 18:18:11.416127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '663fa3a6501b'
down_revision: Union[str, Sequence[str], None] = '161f1645f125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('category', sa.String(), nullable=True))
    op.add_column('foods', sa.Column('default_unit', sa.String(), server_default='gram', nullable=False))
    op.add_column('foods', sa.Column('units', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_column('foods', 'units')
    op.drop_column('foods', 'default_unit')
    op.drop_column('foods', 'category')
    # ### end Alembic commands ###
