"""add_tracking_module

Revision ID: 8fa605be32d8
Revises: a5d90210a60b
Create Date: 2026-01-11 17:35:00.527454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8fa605be32d8'
down_revision: Union[str, Sequence[str], None] = 'a5d90210a60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_daily_logs',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_kcal', sa.Integer(), nullable=False),
    sa.Column('total_protein', sa.Float(), nullable=False),
    sa.Column('total_fat', sa.Float(), nullable=False),
    sa.Column('total_carbs', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_user_date')
    )
    op.create_index(op.f('ix_tracking_daily_logs_date'), 'tracking_daily_logs', ['date'], unique=False)
    op.create_index(op.f('ix_tracking_daily_logs_id'), 'tracking_daily_logs', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_daily_logs_user_id'), 'tracking_daily_logs', ['user_id'], unique=False)
    op.create_table('tracking_meal_entries',
    sa.Column('daily_log_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('amount_grams', sa.Float(), nullable=False),
    sa.Column('kcal_per_100g', sa.Integer(), nullable=False),
    sa.Column('prot_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('carb_per_100g', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['tracking_daily_logs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_meal_entries_daily_log_id'), 'tracking_meal_entries', ['daily_log_id'], unique=False)
    op.create_index(op.f('ix_tracking_meal_entries_id'), 'tracking_meal_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_meal_entries_id'), table_name='tracking_meal_entries')
    op.drop_index(op.f('ix_tracking_meal_entries_daily_log_id'), table_name='tracking_meal_entries')
    op.drop_table('tracking_meal_entries')
    op.drop_index(op.f('ix_tracking_daily_logs_user_id'), table_name='tracking_daily_logs')
    op.drop_index(op.f('ix_tracking_daily_logs_id'), table_name='tracking_daily_logs')
    op.drop_index(op.f('ix_tracking_daily_logs_date'), table_name='tracking_daily_logs')
    op.drop_table('tracking_daily_logs')
    # ### end Alembic commands ###
