"""add unit columns to meal entries

Revision ID: 9b0eade52e8c
Revises: 053a4505bb2d
Create Date: 2026-01-22 03:36:04.066064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0eade52e8c'
down_revision: Union[str, Sequence[str], None] = '053a4505bb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_meal_entries', sa.Column('unit_label', sa.String(), nullable=True))
    op.add_column('tracking_meal_entries', sa.Column('unit_grams', sa.Float(), nullable=True))
    op.add_column('tracking_meal_entries', sa.Column('unit_quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_meal_entries', 'unit_quantity')
    op.drop_column('tracking_meal_entries', 'unit_grams')
    op.drop_column('tracking_meal_entries', 'unit_label')
    # ### end Alembic commands ###
