"""Add popularity score for food

Revision ID: a5d90210a60b
Revises: 8b9b5a6bb1c9
Create Date: 2025-12-01 01:49:42.804222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d90210a60b'
down_revision: Union[str, Sequence[str], None] = '8b9b5a6bb1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('popularity_score', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_foods_popularity_score'), 'foods', ['popularity_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_popularity_score'), table_name='foods')
    op.drop_column('foods', 'popularity_score')
    # ### end Alembic commands ###
