import uuid
from typing import Protocol, Optional, List

from src.food_catalogue.domain.entities import Food


class FoodRepositoryPort(Protocol):
    async def get_by_id(self, id: uuid.UUID) -> Optional[Food]: ...
    async def get_by_barcode(self, barcode: str) -> Optional[Food]: ...
    async def search_by_name(self, query: str, limit: int = 20, owner_id: Optional[uuid.UUID] = None) -> List[Food]: ...
    async def save_custom_food(self, food: Food) -> Food: ...
    async def get_by_source(self, source: str, category: Optional[str] = None, limit: int = 100) -> List[Food]: ...


class ExternalFoodProviderPort(Protocol):
    async def fetch_by_barcode(self, barcode: str) -> Optional[Food]: ...
    async def search(self, query: str, limit: int = 20) -> List[Food]: ...
